-- PostgreSQL. Buat database "carment" dulu di DBeaver, lalu jalankan script ini di dalamnya (Alt+X).
DROP TABLE IF EXISTS inspeksi, maintenance, reservasi, barang, users CASCADE;

CREATE TABLE users (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  hp VARCHAR(20),
  password VARCHAR(255) NOT NULL,
  role VARCHAR(10) NOT NULL DEFAULT 'customer' CHECK (role IN ('customer', 'staff', 'owner'))
);

CREATE TABLE barang (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama VARCHAR(120) NOT NULL,
  kategori VARCHAR(10) NOT NULL CHECK (kategori IN ('Kamera', 'Lensa', 'Aksesori')),
  harga INT NOT NULL,
  deposit INT NOT NULL DEFAULT 0,
  spesifikasi TEXT,
  kondisi TEXT,
  status VARCHAR(12) NOT NULL DEFAULT 'Available' CHECK (status IN ('Available', 'Rented', 'Maintenance'))
);

CREATE TABLE reservasi (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INT NOT NULL REFERENCES users(id),
  barang_id INT NOT NULL REFERENCES barang(id),
  tgl_mulai DATE NOT NULL,
  tgl_selesai DATE NOT NULL,
  sewa INT NOT NULL,
  deposit INT NOT NULL,
  denda INT NOT NULL DEFAULT 0,
  status VARCHAR(12) NOT NULL DEFAULT 'Menunggu' CHECK (status IN ('Menunggu', 'Dikonfirmasi', 'Dipinjam', 'Selesai', 'Ditolak')),
  bukti VARCHAR(100),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_res_barang_tgl ON reservasi(barang_id, tgl_mulai, tgl_selesai);

CREATE TABLE inspeksi (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reservasi_id INT NOT NULL REFERENCES reservasi(id),
  kondisi VARCHAR(5) NOT NULL CHECK (kondisi IN ('Baik', 'Rusak')),
  catatan TEXT,
  tgl DATE NOT NULL
);

CREATE TABLE maintenance (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  barang_id INT NOT NULL REFERENCES barang(id),
  masalah TEXT NOT NULL,
  status VARCHAR(7) NOT NULL DEFAULT 'Dibuka' CHECK (status IN ('Dibuka', 'Selesai')),
  tgl DATE NOT NULL
);

INSERT INTO barang (nama, kategori, harga, deposit, spesifikasi, kondisi) VALUES
('Sony A7 III', 'Kamera', 250000, 1000000, 'Full-frame 24MP, 4K30, dual SD', 'Baik. Goresan halus di body bawah.'),
('Canon EOS R6', 'Kamera', 300000, 1200000, 'Full-frame 20MP, IBIS, 4K60', 'Baik. Karet grip sedikit aus.'),
('Sony FE 24-70mm f/2.8 GM', 'Lensa', 150000, 800000, 'Zoom standar f/2.8, mount Sony E', 'Sangat baik.'),
('Sigma 35mm f/1.4 Art', 'Lensa', 100000, 500000, 'Prime 35mm f/1.4', 'Baik. Tutup lensa belakang hilang.'),
('DJI RS 3 Gimbal', 'Aksesori', 120000, 600000, 'Gimbal 3-axis, beban maks 3 kg', 'Baik. Lengkap dengan plate & tas.');